### ISSUE TITLE
How DICEloss work>?

### ISSUE THREAD

**Issue by GeonSeok-Lee** [a-m-farahani/unet-vessel-segmentation#1]
I'm very impressed your code.

could you explain how DICEloss function work?

**Comment by a-m-farahani** [comment]
Dice-Loss is similar to Intersection over Union(IoU) measure but gives more importance to True Positives and penalizes False Positive and False Negatives. 
Since the inputs of DICELoss function are binary segmentation maps, we can find the intersection by multiplying.
