### ISSUE TITLE
How to support to patch training online?

### ISSUE THREAD

**Issue by David-19940718** [a-m-farahani/unet-vessel-segmentation#2]
Hello, thanks for your nice job! 
Does it support to patch training online? I see your code is directly loading the image.

**Comment by a-m-farahani** [comment]
I'm so sorry I've replied after a long time.
You mean we split images to small patches? Network training is independent from Dataset handling so all you need to do is to edit DatasetHandler class.
In that case you need to change DataSetHandler class and split images to patches and save them in a list, and then in __getitem__ method you need to return a patch or all patches of an image.
